definitions:
  model.BasicResponse:
    properties:
      message:
        type: string
      result: {}
      status:
        type: boolean
    type: object
  server.RBTTransferRequestSwaggoInput:
    properties:
      comment:
        type: string
      receiver:
        type: string
      sender:
        type: string
      tokenCOunt:
        type: number
      type:
        type: integer
    type: object
  server.inputData:
    properties:
      id:
        type: string
      mode:
        type: integer
      password:
        type: string
    type: object
info:
  contact:
    email: murali.c@ensurity.com
    name: API Support
  description: Rubix core API to control & manage the node.
  title: Rubix Core
  version: "0.9"
paths:
  /api/commit-data-token:
    post:
      consumes:
      - application/json
      description: This API will create data token
      parameters:
      - description: DID
        in: query
        name: did
        required: true
        type: string
      - description: Batch ID
        in: query
        name: batchID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Create Data Token
      tags:
      - Data Tokens
  /api/create-data-token:
    post:
      consumes:
      - multipart/form-data
      description: This API will create data token
      parameters:
      - description: DID
        in: formData
        name: did
        required: true
        type: string
      - description: User/Entity ID
        in: formData
        name: UserID
        type: string
      - description: User/Entity Info
        in: formData
        name: UserInfo
        type: string
      - description: Committer DID
        in: formData
        name: CommitterDID
        type: string
      - description: Batch ID
        in: formData
        name: BacthID
        type: string
      - description: File Info is json string {
        in: formData
        name: FileInfo
        type: string
      - description: File to be committed
        in: formData
        name: FileContent
        type: file
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Create Data Token
      tags:
      - Data Tokens
  /api/fetch-smart-contract:
    post:
      consumes:
      - multipart/form-data
      description: This API will deploy smart contract
      parameters:
      - description: smartContractToken
        in: formData
        name: smartContractToken
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Deploy Smart Contract
      tags:
      - Smart Contract
  /api/generate-smart-contract:
    post:
      consumes:
      - multipart/form-data
      description: This API will deploy smart contract
      parameters:
      - description: DID
        in: formData
        name: did
        required: true
        type: string
      - description: location of binary code hash
        in: formData
        name: binaryCodePath
        required: true
        type: file
      - description: location of raw code hash
        in: formData
        name: rawCodePath
        required: true
        type: file
      - description: location of schema code hash
        in: formData
        name: schemaFilePath
        required: true
        type: file
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Deploy Smart Contract
      tags:
      - Smart Contract
  /api/get-account-info:
    get:
      consumes:
      - application/json
      description: For a mentioned DID, check the account balance
      parameters:
      - description: User DID
        in: query
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Check account balance
      tags:
      - Account
  /api/get-by-comment:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a transaction based on its comment.
      operationId: get-by-comment
      parameters:
      - description: Comment to identify the transaction
        in: query
        name: Comment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Get transaction details by Transcation Comment
      tags:
      - Account
  /api/get-by-did:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a transaction based on dID.
      operationId: get-by-did
      parameters:
      - description: DID of sender/receiver
        in: query
        name: DID
        required: true
        type: string
      - description: Filter by role as sender or receiver
        in: query
        name: Role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Get transaction details by dID
      tags:
      - Account
  /api/get-by-txnId:
    get:
      consumes:
      - application/json
      description: Retrieves the details of a transaction based on its ID.
      operationId: get-txn-details-by-id
      parameters:
      - description: The ID of the transaction to retrieve
        in: query
        name: txnID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Get transaction details by Transcation ID
      tags:
      - Account
  /api/get-data-token:
    get:
      consumes:
      - application/json
      description: This API will get all data token belong to the did
      parameters:
      - description: DID
        in: query
        name: did
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Get Data Token
      tags:
      - Data Tokens
  /api/initiate-rbt-transfer:
    post:
      consumes:
      - application/json
      description: Initiates a transfer of RBT tokens from one account to another.
      operationId: initiate-rbt-transfer
      parameters:
      - description: Transfer input parameters
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.RBTTransferRequestSwaggoInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Initiate RBT transfer
      tags:
      - Transaction
  /api/signature-response:
    post:
      consumes:
      - application/json
      description: This API is used to supply the password for the node along with
        the ID generated when Initiate RBT transfer is called.
      operationId: signature-response
      parameters:
      - description: Transfer input parameters
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/server.inputData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Signature Response
      tags:
      - Transaction
  /api/start:
    get:
      consumes:
      - application/json
      description: It will setup the core if not done before
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BasicResponse'
      summary: Start Core
      tags:
      - Basic
securityDefinitions:
  SessionToken:
    in: header
    name: Session-Token
    type: apiKey
swagger: "2.0"
